package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.CureNurseMedicalOrders;
import com.yx.cdss.extract.model.entity.CureNurseMedicalOrdersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CureNurseMedicalOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    long countByExample(CureNurseMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    int deleteByExample(CureNurseMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long nmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    int insert(CureNurseMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    int insertSelective(CureNurseMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    List<CureNurseMedicalOrders> selectByExample(CureNurseMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    CureNurseMedicalOrders selectByPrimaryKey(Long nmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CureNurseMedicalOrders record, @Param("example") CureNurseMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CureNurseMedicalOrders record, @Param("example") CureNurseMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CureNurseMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_nurse_medical_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CureNurseMedicalOrders record);
}