package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.CurePhysiotherapyMedicalOrders;
import com.yx.cdss.extract.model.entity.CurePhysiotherapyMedicalOrdersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CurePhysiotherapyMedicalOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    long countByExample(CurePhysiotherapyMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    int deleteByExample(CurePhysiotherapyMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long nmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    int insert(CurePhysiotherapyMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    int insertSelective(CurePhysiotherapyMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    List<CurePhysiotherapyMedicalOrders> selectByExample(CurePhysiotherapyMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    CurePhysiotherapyMedicalOrders selectByPrimaryKey(Long nmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CurePhysiotherapyMedicalOrders record, @Param("example") CurePhysiotherapyMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CurePhysiotherapyMedicalOrders record, @Param("example") CurePhysiotherapyMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CurePhysiotherapyMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_physiotherapy_medical_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CurePhysiotherapyMedicalOrders record);
}