package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.DictPhysiotherapy;
import com.yx.cdss.extract.model.entity.DictPhysiotherapyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DictPhysiotherapyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    long countByExample(DictPhysiotherapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    int deleteByExample(DictPhysiotherapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long dpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    int insert(DictPhysiotherapy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    int insertSelective(DictPhysiotherapy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    List<DictPhysiotherapy> selectByExample(DictPhysiotherapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    DictPhysiotherapy selectByPrimaryKey(Long dpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DictPhysiotherapy record, @Param("example") DictPhysiotherapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DictPhysiotherapy record, @Param("example") DictPhysiotherapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DictPhysiotherapy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_physiotherapy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DictPhysiotherapy record);
}