package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.DictNurse;
import com.yx.cdss.extract.model.entity.DictNurseExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DictNurseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    long countByExample(DictNurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    int deleteByExample(DictNurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long dnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    int insert(DictNurse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    int insertSelective(DictNurse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    List<DictNurse> selectByExample(DictNurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    DictNurse selectByPrimaryKey(Long dnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DictNurse record, @Param("example") DictNurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DictNurse record, @Param("example") DictNurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DictNurse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_nurse
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DictNurse record);
}