package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.DictExamine;
import com.yx.cdss.extract.model.entity.DictExamineExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DictExamineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    long countByExample(DictExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    int deleteByExample(DictExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long deId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    int insert(DictExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    int insertSelective(DictExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    List<DictExamine> selectByExample(DictExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    DictExamine selectByPrimaryKey(Long deId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DictExamine record, @Param("example") DictExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DictExamine record, @Param("example") DictExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DictExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DictExamine record);
}