package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.DictFrequence;
import com.yx.cdss.extract.model.entity.DictFrequenceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DictFrequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    long countByExample(DictFrequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    int deleteByExample(DictFrequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long dfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    int insert(DictFrequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    int insertSelective(DictFrequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    List<DictFrequence> selectByExample(DictFrequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    DictFrequence selectByPrimaryKey(Long dfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DictFrequence record, @Param("example") DictFrequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DictFrequence record, @Param("example") DictFrequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DictFrequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_frequence
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DictFrequence record);
}