package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.DictExamineNormalvalue;
import com.yx.cdss.extract.model.entity.DictExamineNormalvalueExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DictExamineNormalvalueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    long countByExample(DictExamineNormalvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    int deleteByExample(DictExamineNormalvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long denId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    int insert(DictExamineNormalvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    int insertSelective(DictExamineNormalvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    List<DictExamineNormalvalue> selectByExample(DictExamineNormalvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    DictExamineNormalvalue selectByPrimaryKey(Long denId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DictExamineNormalvalue record, @Param("example") DictExamineNormalvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DictExamineNormalvalue record, @Param("example") DictExamineNormalvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DictExamineNormalvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_examine_normalvalue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DictExamineNormalvalue record);
}