package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.ExamineMedicalOrders;
import com.yx.cdss.extract.model.entity.ExamineMedicalOrdersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExamineMedicalOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    long countByExample(ExamineMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    int deleteByExample(ExamineMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long mmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    int insert(ExamineMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    int insertSelective(ExamineMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    List<ExamineMedicalOrders> selectByExample(ExamineMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    ExamineMedicalOrders selectByPrimaryKey(Long mmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExamineMedicalOrders record, @Param("example") ExamineMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExamineMedicalOrders record, @Param("example") ExamineMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExamineMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_medical_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExamineMedicalOrders record);
}