package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.ExamineInfoReport;
import com.yx.cdss.extract.model.entity.ExamineInfoReportExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExamineInfoReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    long countByExample(ExamineInfoReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    int deleteByExample(ExamineInfoReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long eirId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    int insert(ExamineInfoReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    int insertSelective(ExamineInfoReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    List<ExamineInfoReport> selectByExample(ExamineInfoReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    ExamineInfoReport selectByPrimaryKey(Long eirId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExamineInfoReport record, @Param("example") ExamineInfoReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExamineInfoReport record, @Param("example") ExamineInfoReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExamineInfoReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExamineInfoReport record);
}