package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.InspectMedicalOrders;
import com.yx.cdss.extract.model.entity.InspectMedicalOrdersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface InspectMedicalOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    long countByExample(InspectMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    int deleteByExample(InspectMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long mmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    int insert(InspectMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    int insertSelective(InspectMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    List<InspectMedicalOrders> selectByExample(InspectMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    InspectMedicalOrders selectByPrimaryKey(Long mmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InspectMedicalOrders record, @Param("example") InspectMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InspectMedicalOrders record, @Param("example") InspectMedicalOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InspectMedicalOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_medical_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InspectMedicalOrders record);
}