package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.PatientInhospital;
import com.yx.cdss.extract.model.entity.PatientInhospitalExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PatientInhospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    long countByExample(PatientInhospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int deleteByExample(PatientInhospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long piId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int insert(PatientInhospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int insertSelective(PatientInhospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    List<PatientInhospital> selectByExampleWithBLOBs(PatientInhospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    List<PatientInhospital> selectByExample(PatientInhospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    PatientInhospital selectByPrimaryKey(Long piId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PatientInhospital record, @Param("example") PatientInhospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PatientInhospital record, @Param("example") PatientInhospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PatientInhospital record, @Param("example") PatientInhospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PatientInhospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PatientInhospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_inhospital
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PatientInhospital record);
}