package com.yx.cdss.extract.model.mapper;

import com.yx.cdss.extract.model.entity.PatientBaseInfo;
import com.yx.cdss.extract.model.entity.PatientBaseInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PatientBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    long countByExample(PatientBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    int deleteByExample(PatientBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long pbiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    int insert(PatientBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    int insertSelective(PatientBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    List<PatientBaseInfo> selectByExample(PatientBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    PatientBaseInfo selectByPrimaryKey(Long pbiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PatientBaseInfo record, @Param("example") PatientBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PatientBaseInfo record, @Param("example") PatientBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PatientBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_base_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PatientBaseInfo record);
}