package com.yx.cdss.extract.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CureSurgeryInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public CureSurgeryInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCsrIdIsNull() {
            addCriterion("csr_id is null");
            return (Criteria) this;
        }

        public Criteria andCsrIdIsNotNull() {
            addCriterion("csr_id is not null");
            return (Criteria) this;
        }

        public Criteria andCsrIdEqualTo(Long value) {
            addCriterion("csr_id =", value, "csrId");
            return (Criteria) this;
        }

        public Criteria andCsrIdNotEqualTo(Long value) {
            addCriterion("csr_id <>", value, "csrId");
            return (Criteria) this;
        }

        public Criteria andCsrIdGreaterThan(Long value) {
            addCriterion("csr_id >", value, "csrId");
            return (Criteria) this;
        }

        public Criteria andCsrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("csr_id >=", value, "csrId");
            return (Criteria) this;
        }

        public Criteria andCsrIdLessThan(Long value) {
            addCriterion("csr_id <", value, "csrId");
            return (Criteria) this;
        }

        public Criteria andCsrIdLessThanOrEqualTo(Long value) {
            addCriterion("csr_id <=", value, "csrId");
            return (Criteria) this;
        }

        public Criteria andCsrIdIn(List<Long> values) {
            addCriterion("csr_id in", values, "csrId");
            return (Criteria) this;
        }

        public Criteria andCsrIdNotIn(List<Long> values) {
            addCriterion("csr_id not in", values, "csrId");
            return (Criteria) this;
        }

        public Criteria andCsrIdBetween(Long value1, Long value2) {
            addCriterion("csr_id between", value1, value2, "csrId");
            return (Criteria) this;
        }

        public Criteria andCsrIdNotBetween(Long value1, Long value2) {
            addCriterion("csr_id not between", value1, value2, "csrId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("patient_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("patient_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(String value) {
            addCriterion("patient_id =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(String value) {
            addCriterion("patient_id <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(String value) {
            addCriterion("patient_id >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
            addCriterion("patient_id >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(String value) {
            addCriterion("patient_id <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(String value) {
            addCriterion("patient_id <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLike(String value) {
            addCriterion("patient_id like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotLike(String value) {
            addCriterion("patient_id not like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<String> values) {
            addCriterion("patient_id in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<String> values) {
            addCriterion("patient_id not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(String value1, String value2) {
            addCriterion("patient_id between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(String value1, String value2) {
            addCriterion("patient_id not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andSurgNameIsNull() {
            addCriterion("surg_name is null");
            return (Criteria) this;
        }

        public Criteria andSurgNameIsNotNull() {
            addCriterion("surg_name is not null");
            return (Criteria) this;
        }

        public Criteria andSurgNameEqualTo(String value) {
            addCriterion("surg_name =", value, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameNotEqualTo(String value) {
            addCriterion("surg_name <>", value, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameGreaterThan(String value) {
            addCriterion("surg_name >", value, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameGreaterThanOrEqualTo(String value) {
            addCriterion("surg_name >=", value, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameLessThan(String value) {
            addCriterion("surg_name <", value, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameLessThanOrEqualTo(String value) {
            addCriterion("surg_name <=", value, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameLike(String value) {
            addCriterion("surg_name like", value, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameNotLike(String value) {
            addCriterion("surg_name not like", value, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameIn(List<String> values) {
            addCriterion("surg_name in", values, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameNotIn(List<String> values) {
            addCriterion("surg_name not in", values, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameBetween(String value1, String value2) {
            addCriterion("surg_name between", value1, value2, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgNameNotBetween(String value1, String value2) {
            addCriterion("surg_name not between", value1, value2, "surgName");
            return (Criteria) this;
        }

        public Criteria andSurgTimeIsNull() {
            addCriterion("surg_time is null");
            return (Criteria) this;
        }

        public Criteria andSurgTimeIsNotNull() {
            addCriterion("surg_time is not null");
            return (Criteria) this;
        }

        public Criteria andSurgTimeEqualTo(Date value) {
            addCriterion("surg_time =", value, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgTimeNotEqualTo(Date value) {
            addCriterion("surg_time <>", value, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgTimeGreaterThan(Date value) {
            addCriterion("surg_time >", value, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("surg_time >=", value, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgTimeLessThan(Date value) {
            addCriterion("surg_time <", value, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgTimeLessThanOrEqualTo(Date value) {
            addCriterion("surg_time <=", value, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgTimeIn(List<Date> values) {
            addCriterion("surg_time in", values, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgTimeNotIn(List<Date> values) {
            addCriterion("surg_time not in", values, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgTimeBetween(Date value1, Date value2) {
            addCriterion("surg_time between", value1, value2, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgTimeNotBetween(Date value1, Date value2) {
            addCriterion("surg_time not between", value1, value2, "surgTime");
            return (Criteria) this;
        }

        public Criteria andSurgCodeIsNull() {
            addCriterion("surg_code is null");
            return (Criteria) this;
        }

        public Criteria andSurgCodeIsNotNull() {
            addCriterion("surg_code is not null");
            return (Criteria) this;
        }

        public Criteria andSurgCodeEqualTo(String value) {
            addCriterion("surg_code =", value, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeNotEqualTo(String value) {
            addCriterion("surg_code <>", value, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeGreaterThan(String value) {
            addCriterion("surg_code >", value, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("surg_code >=", value, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeLessThan(String value) {
            addCriterion("surg_code <", value, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeLessThanOrEqualTo(String value) {
            addCriterion("surg_code <=", value, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeLike(String value) {
            addCriterion("surg_code like", value, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeNotLike(String value) {
            addCriterion("surg_code not like", value, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeIn(List<String> values) {
            addCriterion("surg_code in", values, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeNotIn(List<String> values) {
            addCriterion("surg_code not in", values, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeBetween(String value1, String value2) {
            addCriterion("surg_code between", value1, value2, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgCodeNotBetween(String value1, String value2) {
            addCriterion("surg_code not between", value1, value2, "surgCode");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoIsNull() {
            addCriterion("surg_application_no is null");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoIsNotNull() {
            addCriterion("surg_application_no is not null");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoEqualTo(String value) {
            addCriterion("surg_application_no =", value, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoNotEqualTo(String value) {
            addCriterion("surg_application_no <>", value, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoGreaterThan(String value) {
            addCriterion("surg_application_no >", value, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoGreaterThanOrEqualTo(String value) {
            addCriterion("surg_application_no >=", value, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoLessThan(String value) {
            addCriterion("surg_application_no <", value, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoLessThanOrEqualTo(String value) {
            addCriterion("surg_application_no <=", value, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoLike(String value) {
            addCriterion("surg_application_no like", value, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoNotLike(String value) {
            addCriterion("surg_application_no not like", value, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoIn(List<String> values) {
            addCriterion("surg_application_no in", values, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoNotIn(List<String> values) {
            addCriterion("surg_application_no not in", values, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoBetween(String value1, String value2) {
            addCriterion("surg_application_no between", value1, value2, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgApplicationNoNotBetween(String value1, String value2) {
            addCriterion("surg_application_no not between", value1, value2, "surgApplicationNo");
            return (Criteria) this;
        }

        public Criteria andSurgLevelIsNull() {
            addCriterion("surg_level is null");
            return (Criteria) this;
        }

        public Criteria andSurgLevelIsNotNull() {
            addCriterion("surg_level is not null");
            return (Criteria) this;
        }

        public Criteria andSurgLevelEqualTo(String value) {
            addCriterion("surg_level =", value, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelNotEqualTo(String value) {
            addCriterion("surg_level <>", value, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelGreaterThan(String value) {
            addCriterion("surg_level >", value, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelGreaterThanOrEqualTo(String value) {
            addCriterion("surg_level >=", value, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelLessThan(String value) {
            addCriterion("surg_level <", value, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelLessThanOrEqualTo(String value) {
            addCriterion("surg_level <=", value, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelLike(String value) {
            addCriterion("surg_level like", value, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelNotLike(String value) {
            addCriterion("surg_level not like", value, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelIn(List<String> values) {
            addCriterion("surg_level in", values, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelNotIn(List<String> values) {
            addCriterion("surg_level not in", values, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelBetween(String value1, String value2) {
            addCriterion("surg_level between", value1, value2, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgLevelNotBetween(String value1, String value2) {
            addCriterion("surg_level not between", value1, value2, "surgLevel");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorIsNull() {
            addCriterion("surg_doctor is null");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorIsNotNull() {
            addCriterion("surg_doctor is not null");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorEqualTo(String value) {
            addCriterion("surg_doctor =", value, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorNotEqualTo(String value) {
            addCriterion("surg_doctor <>", value, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorGreaterThan(String value) {
            addCriterion("surg_doctor >", value, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorGreaterThanOrEqualTo(String value) {
            addCriterion("surg_doctor >=", value, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorLessThan(String value) {
            addCriterion("surg_doctor <", value, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorLessThanOrEqualTo(String value) {
            addCriterion("surg_doctor <=", value, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorLike(String value) {
            addCriterion("surg_doctor like", value, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorNotLike(String value) {
            addCriterion("surg_doctor not like", value, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorIn(List<String> values) {
            addCriterion("surg_doctor in", values, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorNotIn(List<String> values) {
            addCriterion("surg_doctor not in", values, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorBetween(String value1, String value2) {
            addCriterion("surg_doctor between", value1, value2, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andSurgDoctorNotBetween(String value1, String value2) {
            addCriterion("surg_doctor not between", value1, value2, "surgDoctor");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelIsNull() {
            addCriterion("docktor_level is null");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelIsNotNull() {
            addCriterion("docktor_level is not null");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelEqualTo(String value) {
            addCriterion("docktor_level =", value, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelNotEqualTo(String value) {
            addCriterion("docktor_level <>", value, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelGreaterThan(String value) {
            addCriterion("docktor_level >", value, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelGreaterThanOrEqualTo(String value) {
            addCriterion("docktor_level >=", value, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelLessThan(String value) {
            addCriterion("docktor_level <", value, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelLessThanOrEqualTo(String value) {
            addCriterion("docktor_level <=", value, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelLike(String value) {
            addCriterion("docktor_level like", value, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelNotLike(String value) {
            addCriterion("docktor_level not like", value, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelIn(List<String> values) {
            addCriterion("docktor_level in", values, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelNotIn(List<String> values) {
            addCriterion("docktor_level not in", values, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelBetween(String value1, String value2) {
            addCriterion("docktor_level between", value1, value2, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDocktorLevelNotBetween(String value1, String value2) {
            addCriterion("docktor_level not between", value1, value2, "docktorLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeIsNull() {
            addCriterion("doctor_code is null");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeIsNotNull() {
            addCriterion("doctor_code is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeEqualTo(String value) {
            addCriterion("doctor_code =", value, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeNotEqualTo(String value) {
            addCriterion("doctor_code <>", value, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeGreaterThan(String value) {
            addCriterion("doctor_code >", value, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_code >=", value, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeLessThan(String value) {
            addCriterion("doctor_code <", value, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeLessThanOrEqualTo(String value) {
            addCriterion("doctor_code <=", value, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeLike(String value) {
            addCriterion("doctor_code like", value, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeNotLike(String value) {
            addCriterion("doctor_code not like", value, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeIn(List<String> values) {
            addCriterion("doctor_code in", values, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeNotIn(List<String> values) {
            addCriterion("doctor_code not in", values, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeBetween(String value1, String value2) {
            addCriterion("doctor_code between", value1, value2, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andDoctorCodeNotBetween(String value1, String value2) {
            addCriterion("doctor_code not between", value1, value2, "doctorCode");
            return (Criteria) this;
        }

        public Criteria andExtractTimeIsNull() {
            addCriterion("extract_time is null");
            return (Criteria) this;
        }

        public Criteria andExtractTimeIsNotNull() {
            addCriterion("extract_time is not null");
            return (Criteria) this;
        }

        public Criteria andExtractTimeEqualTo(Date value) {
            addCriterion("extract_time =", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeNotEqualTo(Date value) {
            addCriterion("extract_time <>", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeGreaterThan(Date value) {
            addCriterion("extract_time >", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("extract_time >=", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeLessThan(Date value) {
            addCriterion("extract_time <", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeLessThanOrEqualTo(Date value) {
            addCriterion("extract_time <=", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeIn(List<Date> values) {
            addCriterion("extract_time in", values, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeNotIn(List<Date> values) {
            addCriterion("extract_time not in", values, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeBetween(Date value1, Date value2) {
            addCriterion("extract_time between", value1, value2, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeNotBetween(Date value1, Date value2) {
            addCriterion("extract_time not between", value1, value2, "extractTime");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNull() {
            addCriterion("record_status is null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNotNull() {
            addCriterion("record_status is not null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusEqualTo(Integer value) {
            addCriterion("record_status =", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotEqualTo(Integer value) {
            addCriterion("record_status <>", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThan(Integer value) {
            addCriterion("record_status >", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_status >=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThan(Integer value) {
            addCriterion("record_status <", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThanOrEqualTo(Integer value) {
            addCriterion("record_status <=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIn(List<Integer> values) {
            addCriterion("record_status in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotIn(List<Integer> values) {
            addCriterion("record_status not in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusBetween(Integer value1, Integer value2) {
            addCriterion("record_status between", value1, value2, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("record_status not between", value1, value2, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNull() {
            addCriterion("attribute1 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNotNull() {
            addCriterion("attribute1 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute1EqualTo(String value) {
            addCriterion("attribute1 =", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotEqualTo(String value) {
            addCriterion("attribute1 <>", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThan(String value) {
            addCriterion("attribute1 >", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThanOrEqualTo(String value) {
            addCriterion("attribute1 >=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThan(String value) {
            addCriterion("attribute1 <", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThanOrEqualTo(String value) {
            addCriterion("attribute1 <=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Like(String value) {
            addCriterion("attribute1 like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotLike(String value) {
            addCriterion("attribute1 not like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1In(List<String> values) {
            addCriterion("attribute1 in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotIn(List<String> values) {
            addCriterion("attribute1 not in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Between(String value1, String value2) {
            addCriterion("attribute1 between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotBetween(String value1, String value2) {
            addCriterion("attribute1 not between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNull() {
            addCriterion("attribute2 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNotNull() {
            addCriterion("attribute2 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute2EqualTo(String value) {
            addCriterion("attribute2 =", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotEqualTo(String value) {
            addCriterion("attribute2 <>", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThan(String value) {
            addCriterion("attribute2 >", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThanOrEqualTo(String value) {
            addCriterion("attribute2 >=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThan(String value) {
            addCriterion("attribute2 <", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThanOrEqualTo(String value) {
            addCriterion("attribute2 <=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Like(String value) {
            addCriterion("attribute2 like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotLike(String value) {
            addCriterion("attribute2 not like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2In(List<String> values) {
            addCriterion("attribute2 in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotIn(List<String> values) {
            addCriterion("attribute2 not in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Between(String value1, String value2) {
            addCriterion("attribute2 between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotBetween(String value1, String value2) {
            addCriterion("attribute2 not between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNull() {
            addCriterion("attribute3 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNotNull() {
            addCriterion("attribute3 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute3EqualTo(String value) {
            addCriterion("attribute3 =", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotEqualTo(String value) {
            addCriterion("attribute3 <>", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThan(String value) {
            addCriterion("attribute3 >", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThanOrEqualTo(String value) {
            addCriterion("attribute3 >=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThan(String value) {
            addCriterion("attribute3 <", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThanOrEqualTo(String value) {
            addCriterion("attribute3 <=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Like(String value) {
            addCriterion("attribute3 like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotLike(String value) {
            addCriterion("attribute3 not like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3In(List<String> values) {
            addCriterion("attribute3 in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotIn(List<String> values) {
            addCriterion("attribute3 not in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Between(String value1, String value2) {
            addCriterion("attribute3 between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotBetween(String value1, String value2) {
            addCriterion("attribute3 not between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute4IsNull() {
            addCriterion("attribute4 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute4IsNotNull() {
            addCriterion("attribute4 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute4EqualTo(String value) {
            addCriterion("attribute4 =", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotEqualTo(String value) {
            addCriterion("attribute4 <>", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4GreaterThan(String value) {
            addCriterion("attribute4 >", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4GreaterThanOrEqualTo(String value) {
            addCriterion("attribute4 >=", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4LessThan(String value) {
            addCriterion("attribute4 <", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4LessThanOrEqualTo(String value) {
            addCriterion("attribute4 <=", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4Like(String value) {
            addCriterion("attribute4 like", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotLike(String value) {
            addCriterion("attribute4 not like", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4In(List<String> values) {
            addCriterion("attribute4 in", values, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotIn(List<String> values) {
            addCriterion("attribute4 not in", values, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4Between(String value1, String value2) {
            addCriterion("attribute4 between", value1, value2, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotBetween(String value1, String value2) {
            addCriterion("attribute4 not between", value1, value2, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute5IsNull() {
            addCriterion("attribute5 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute5IsNotNull() {
            addCriterion("attribute5 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute5EqualTo(String value) {
            addCriterion("attribute5 =", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotEqualTo(String value) {
            addCriterion("attribute5 <>", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5GreaterThan(String value) {
            addCriterion("attribute5 >", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5GreaterThanOrEqualTo(String value) {
            addCriterion("attribute5 >=", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5LessThan(String value) {
            addCriterion("attribute5 <", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5LessThanOrEqualTo(String value) {
            addCriterion("attribute5 <=", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5Like(String value) {
            addCriterion("attribute5 like", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotLike(String value) {
            addCriterion("attribute5 not like", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5In(List<String> values) {
            addCriterion("attribute5 in", values, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotIn(List<String> values) {
            addCriterion("attribute5 not in", values, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5Between(String value1, String value2) {
            addCriterion("attribute5 between", value1, value2, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotBetween(String value1, String value2) {
            addCriterion("attribute5 not between", value1, value2, "attribute5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cure_surgery_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cure_surgery_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}