package com.yx.cdss.extract.model.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dict_dose_unit
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DictDoseUnit implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_dose_unit.ddu_id
     *
     * @mbg.generated
     */
    private Long dduId;

    /**
     * Database Column Remarks:
     *   剂量单位名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_dose_unit.dose_unit_name
     *
     * @mbg.generated
     */
    private String doseUnitName;

    /**
     * Database Column Remarks:
     *   剂量单位编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_dose_unit.dose_unit_code
     *
     * @mbg.generated
     */
    private String doseUnitCode;

    /**
     * Database Column Remarks:
     *   抽取时间,数据同步
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_dose_unit.extract_time
     *
     * @mbg.generated
     */
    private Date extractTime;

    /**
     * Database Column Remarks:
     *   预留字段1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_dose_unit.attribute1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     * Database Column Remarks:
     *   预留字段2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_dose_unit.attribute2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     * Database Column Remarks:
     *   预留字段3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_dose_unit.attribute3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     * Database Column Remarks:
     *   预留字段4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_dose_unit.attribute4
     *
     * @mbg.generated
     */
    private String attribute4;

    /**
     * Database Column Remarks:
     *   预留字段5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_dose_unit.attribute5
     *
     * @mbg.generated
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_dose_unit
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_dose_unit.ddu_id
     *
     * @return the value of dict_dose_unit.ddu_id
     *
     * @mbg.generated
     */
    public Long getDduId() {
        return dduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_dose_unit.ddu_id
     *
     * @param dduId the value for dict_dose_unit.ddu_id
     *
     * @mbg.generated
     */
    public void setDduId(Long dduId) {
        this.dduId = dduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_dose_unit.dose_unit_name
     *
     * @return the value of dict_dose_unit.dose_unit_name
     *
     * @mbg.generated
     */
    public String getDoseUnitName() {
        return doseUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_dose_unit.dose_unit_name
     *
     * @param doseUnitName the value for dict_dose_unit.dose_unit_name
     *
     * @mbg.generated
     */
    public void setDoseUnitName(String doseUnitName) {
        this.doseUnitName = doseUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_dose_unit.dose_unit_code
     *
     * @return the value of dict_dose_unit.dose_unit_code
     *
     * @mbg.generated
     */
    public String getDoseUnitCode() {
        return doseUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_dose_unit.dose_unit_code
     *
     * @param doseUnitCode the value for dict_dose_unit.dose_unit_code
     *
     * @mbg.generated
     */
    public void setDoseUnitCode(String doseUnitCode) {
        this.doseUnitCode = doseUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_dose_unit.extract_time
     *
     * @return the value of dict_dose_unit.extract_time
     *
     * @mbg.generated
     */
    public Date getExtractTime() {
        return extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_dose_unit.extract_time
     *
     * @param extractTime the value for dict_dose_unit.extract_time
     *
     * @mbg.generated
     */
    public void setExtractTime(Date extractTime) {
        this.extractTime = extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_dose_unit.attribute1
     *
     * @return the value of dict_dose_unit.attribute1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_dose_unit.attribute1
     *
     * @param attribute1 the value for dict_dose_unit.attribute1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_dose_unit.attribute2
     *
     * @return the value of dict_dose_unit.attribute2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_dose_unit.attribute2
     *
     * @param attribute2 the value for dict_dose_unit.attribute2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_dose_unit.attribute3
     *
     * @return the value of dict_dose_unit.attribute3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_dose_unit.attribute3
     *
     * @param attribute3 the value for dict_dose_unit.attribute3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_dose_unit.attribute4
     *
     * @return the value of dict_dose_unit.attribute4
     *
     * @mbg.generated
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_dose_unit.attribute4
     *
     * @param attribute4 the value for dict_dose_unit.attribute4
     *
     * @mbg.generated
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_dose_unit.attribute5
     *
     * @return the value of dict_dose_unit.attribute5
     *
     * @mbg.generated
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_dose_unit.attribute5
     *
     * @param attribute5 the value for dict_dose_unit.attribute5
     *
     * @mbg.generated
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
}