package com.yx.cdss.extract.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DrugMedicaLordersDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public DrugMedicaLordersDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDmldIsNull() {
            addCriterion("dmld is null");
            return (Criteria) this;
        }

        public Criteria andDmldIsNotNull() {
            addCriterion("dmld is not null");
            return (Criteria) this;
        }

        public Criteria andDmldEqualTo(Long value) {
            addCriterion("dmld =", value, "dmld");
            return (Criteria) this;
        }

        public Criteria andDmldNotEqualTo(Long value) {
            addCriterion("dmld <>", value, "dmld");
            return (Criteria) this;
        }

        public Criteria andDmldGreaterThan(Long value) {
            addCriterion("dmld >", value, "dmld");
            return (Criteria) this;
        }

        public Criteria andDmldGreaterThanOrEqualTo(Long value) {
            addCriterion("dmld >=", value, "dmld");
            return (Criteria) this;
        }

        public Criteria andDmldLessThan(Long value) {
            addCriterion("dmld <", value, "dmld");
            return (Criteria) this;
        }

        public Criteria andDmldLessThanOrEqualTo(Long value) {
            addCriterion("dmld <=", value, "dmld");
            return (Criteria) this;
        }

        public Criteria andDmldIn(List<Long> values) {
            addCriterion("dmld in", values, "dmld");
            return (Criteria) this;
        }

        public Criteria andDmldNotIn(List<Long> values) {
            addCriterion("dmld not in", values, "dmld");
            return (Criteria) this;
        }

        public Criteria andDmldBetween(Long value1, Long value2) {
            addCriterion("dmld between", value1, value2, "dmld");
            return (Criteria) this;
        }

        public Criteria andDmldNotBetween(Long value1, Long value2) {
            addCriterion("dmld not between", value1, value2, "dmld");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdIsNull() {
            addCriterion("medical_orders_id is null");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdIsNotNull() {
            addCriterion("medical_orders_id is not null");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdEqualTo(String value) {
            addCriterion("medical_orders_id =", value, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdNotEqualTo(String value) {
            addCriterion("medical_orders_id <>", value, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdGreaterThan(String value) {
            addCriterion("medical_orders_id >", value, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdGreaterThanOrEqualTo(String value) {
            addCriterion("medical_orders_id >=", value, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdLessThan(String value) {
            addCriterion("medical_orders_id <", value, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdLessThanOrEqualTo(String value) {
            addCriterion("medical_orders_id <=", value, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdLike(String value) {
            addCriterion("medical_orders_id like", value, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdNotLike(String value) {
            addCriterion("medical_orders_id not like", value, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdIn(List<String> values) {
            addCriterion("medical_orders_id in", values, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdNotIn(List<String> values) {
            addCriterion("medical_orders_id not in", values, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdBetween(String value1, String value2) {
            addCriterion("medical_orders_id between", value1, value2, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andMedicalOrdersIdNotBetween(String value1, String value2) {
            addCriterion("medical_orders_id not between", value1, value2, "medicalOrdersId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("patient_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("patient_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(String value) {
            addCriterion("patient_id =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(String value) {
            addCriterion("patient_id <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(String value) {
            addCriterion("patient_id >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
            addCriterion("patient_id >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(String value) {
            addCriterion("patient_id <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(String value) {
            addCriterion("patient_id <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLike(String value) {
            addCriterion("patient_id like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotLike(String value) {
            addCriterion("patient_id not like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<String> values) {
            addCriterion("patient_id in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<String> values) {
            addCriterion("patient_id not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(String value1, String value2) {
            addCriterion("patient_id between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(String value1, String value2) {
            addCriterion("patient_id not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberIsNull() {
            addCriterion("admission_number is null");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberIsNotNull() {
            addCriterion("admission_number is not null");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberEqualTo(String value) {
            addCriterion("admission_number =", value, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberNotEqualTo(String value) {
            addCriterion("admission_number <>", value, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberGreaterThan(String value) {
            addCriterion("admission_number >", value, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberGreaterThanOrEqualTo(String value) {
            addCriterion("admission_number >=", value, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberLessThan(String value) {
            addCriterion("admission_number <", value, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberLessThanOrEqualTo(String value) {
            addCriterion("admission_number <=", value, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberLike(String value) {
            addCriterion("admission_number like", value, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberNotLike(String value) {
            addCriterion("admission_number not like", value, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberIn(List<String> values) {
            addCriterion("admission_number in", values, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberNotIn(List<String> values) {
            addCriterion("admission_number not in", values, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberBetween(String value1, String value2) {
            addCriterion("admission_number between", value1, value2, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andAdmissionNumberNotBetween(String value1, String value2) {
            addCriterion("admission_number not between", value1, value2, "admissionNumber");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIsNull() {
            addCriterion("group_code is null");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIsNotNull() {
            addCriterion("group_code is not null");
            return (Criteria) this;
        }

        public Criteria andGroupCodeEqualTo(String value) {
            addCriterion("group_code =", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotEqualTo(String value) {
            addCriterion("group_code <>", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeGreaterThan(String value) {
            addCriterion("group_code >", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeGreaterThanOrEqualTo(String value) {
            addCriterion("group_code >=", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLessThan(String value) {
            addCriterion("group_code <", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLessThanOrEqualTo(String value) {
            addCriterion("group_code <=", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLike(String value) {
            addCriterion("group_code like", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotLike(String value) {
            addCriterion("group_code not like", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIn(List<String> values) {
            addCriterion("group_code in", values, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotIn(List<String> values) {
            addCriterion("group_code not in", values, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeBetween(String value1, String value2) {
            addCriterion("group_code between", value1, value2, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotBetween(String value1, String value2) {
            addCriterion("group_code not between", value1, value2, "groupCode");
            return (Criteria) this;
        }

        public Criteria andDrugNameIsNull() {
            addCriterion("drug_name is null");
            return (Criteria) this;
        }

        public Criteria andDrugNameIsNotNull() {
            addCriterion("drug_name is not null");
            return (Criteria) this;
        }

        public Criteria andDrugNameEqualTo(String value) {
            addCriterion("drug_name =", value, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameNotEqualTo(String value) {
            addCriterion("drug_name <>", value, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameGreaterThan(String value) {
            addCriterion("drug_name >", value, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameGreaterThanOrEqualTo(String value) {
            addCriterion("drug_name >=", value, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameLessThan(String value) {
            addCriterion("drug_name <", value, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameLessThanOrEqualTo(String value) {
            addCriterion("drug_name <=", value, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameLike(String value) {
            addCriterion("drug_name like", value, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameNotLike(String value) {
            addCriterion("drug_name not like", value, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameIn(List<String> values) {
            addCriterion("drug_name in", values, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameNotIn(List<String> values) {
            addCriterion("drug_name not in", values, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameBetween(String value1, String value2) {
            addCriterion("drug_name between", value1, value2, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugNameNotBetween(String value1, String value2) {
            addCriterion("drug_name not between", value1, value2, "drugName");
            return (Criteria) this;
        }

        public Criteria andDrugCodeIsNull() {
            addCriterion("drug_code is null");
            return (Criteria) this;
        }

        public Criteria andDrugCodeIsNotNull() {
            addCriterion("drug_code is not null");
            return (Criteria) this;
        }

        public Criteria andDrugCodeEqualTo(String value) {
            addCriterion("drug_code =", value, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeNotEqualTo(String value) {
            addCriterion("drug_code <>", value, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeGreaterThan(String value) {
            addCriterion("drug_code >", value, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeGreaterThanOrEqualTo(String value) {
            addCriterion("drug_code >=", value, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeLessThan(String value) {
            addCriterion("drug_code <", value, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeLessThanOrEqualTo(String value) {
            addCriterion("drug_code <=", value, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeLike(String value) {
            addCriterion("drug_code like", value, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeNotLike(String value) {
            addCriterion("drug_code not like", value, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeIn(List<String> values) {
            addCriterion("drug_code in", values, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeNotIn(List<String> values) {
            addCriterion("drug_code not in", values, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeBetween(String value1, String value2) {
            addCriterion("drug_code between", value1, value2, "drugCode");
            return (Criteria) this;
        }

        public Criteria andDrugCodeNotBetween(String value1, String value2) {
            addCriterion("drug_code not between", value1, value2, "drugCode");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsIsNull() {
            addCriterion("frequent_of_medications is null");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsIsNotNull() {
            addCriterion("frequent_of_medications is not null");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsEqualTo(Integer value) {
            addCriterion("frequent_of_medications =", value, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsNotEqualTo(Integer value) {
            addCriterion("frequent_of_medications <>", value, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsGreaterThan(Integer value) {
            addCriterion("frequent_of_medications >", value, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsGreaterThanOrEqualTo(Integer value) {
            addCriterion("frequent_of_medications >=", value, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsLessThan(Integer value) {
            addCriterion("frequent_of_medications <", value, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsLessThanOrEqualTo(Integer value) {
            addCriterion("frequent_of_medications <=", value, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsIn(List<Integer> values) {
            addCriterion("frequent_of_medications in", values, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsNotIn(List<Integer> values) {
            addCriterion("frequent_of_medications not in", values, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsBetween(Integer value1, Integer value2) {
            addCriterion("frequent_of_medications between", value1, value2, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andFrequentOfMedicationsNotBetween(Integer value1, Integer value2) {
            addCriterion("frequent_of_medications not between", value1, value2, "frequentOfMedications");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalIsNull() {
            addCriterion("dose_of_einmal is null");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalIsNotNull() {
            addCriterion("dose_of_einmal is not null");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalEqualTo(Double value) {
            addCriterion("dose_of_einmal =", value, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalNotEqualTo(Double value) {
            addCriterion("dose_of_einmal <>", value, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalGreaterThan(Double value) {
            addCriterion("dose_of_einmal >", value, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalGreaterThanOrEqualTo(Double value) {
            addCriterion("dose_of_einmal >=", value, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalLessThan(Double value) {
            addCriterion("dose_of_einmal <", value, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalLessThanOrEqualTo(Double value) {
            addCriterion("dose_of_einmal <=", value, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalIn(List<Double> values) {
            addCriterion("dose_of_einmal in", values, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalNotIn(List<Double> values) {
            addCriterion("dose_of_einmal not in", values, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalBetween(Double value1, Double value2) {
            addCriterion("dose_of_einmal between", value1, value2, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseOfEinmalNotBetween(Double value1, Double value2) {
            addCriterion("dose_of_einmal not between", value1, value2, "doseOfEinmal");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsIsNull() {
            addCriterion("dose_units is null");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsIsNotNull() {
            addCriterion("dose_units is not null");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsEqualTo(String value) {
            addCriterion("dose_units =", value, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsNotEqualTo(String value) {
            addCriterion("dose_units <>", value, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsGreaterThan(String value) {
            addCriterion("dose_units >", value, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsGreaterThanOrEqualTo(String value) {
            addCriterion("dose_units >=", value, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsLessThan(String value) {
            addCriterion("dose_units <", value, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsLessThanOrEqualTo(String value) {
            addCriterion("dose_units <=", value, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsLike(String value) {
            addCriterion("dose_units like", value, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsNotLike(String value) {
            addCriterion("dose_units not like", value, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsIn(List<String> values) {
            addCriterion("dose_units in", values, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsNotIn(List<String> values) {
            addCriterion("dose_units not in", values, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsBetween(String value1, String value2) {
            addCriterion("dose_units between", value1, value2, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andDoseUnitsNotBetween(String value1, String value2) {
            addCriterion("dose_units not between", value1, value2, "doseUnits");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugIsNull() {
            addCriterion("route_of_given_drug is null");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugIsNotNull() {
            addCriterion("route_of_given_drug is not null");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugEqualTo(String value) {
            addCriterion("route_of_given_drug =", value, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugNotEqualTo(String value) {
            addCriterion("route_of_given_drug <>", value, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugGreaterThan(String value) {
            addCriterion("route_of_given_drug >", value, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugGreaterThanOrEqualTo(String value) {
            addCriterion("route_of_given_drug >=", value, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugLessThan(String value) {
            addCriterion("route_of_given_drug <", value, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugLessThanOrEqualTo(String value) {
            addCriterion("route_of_given_drug <=", value, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugLike(String value) {
            addCriterion("route_of_given_drug like", value, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugNotLike(String value) {
            addCriterion("route_of_given_drug not like", value, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugIn(List<String> values) {
            addCriterion("route_of_given_drug in", values, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugNotIn(List<String> values) {
            addCriterion("route_of_given_drug not in", values, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugBetween(String value1, String value2) {
            addCriterion("route_of_given_drug between", value1, value2, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andRouteOfGivenDrugNotBetween(String value1, String value2) {
            addCriterion("route_of_given_drug not between", value1, value2, "routeOfGivenDrug");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsIsNull() {
            addCriterion("drug_specifications is null");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsIsNotNull() {
            addCriterion("drug_specifications is not null");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsEqualTo(String value) {
            addCriterion("drug_specifications =", value, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsNotEqualTo(String value) {
            addCriterion("drug_specifications <>", value, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsGreaterThan(String value) {
            addCriterion("drug_specifications >", value, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsGreaterThanOrEqualTo(String value) {
            addCriterion("drug_specifications >=", value, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsLessThan(String value) {
            addCriterion("drug_specifications <", value, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsLessThanOrEqualTo(String value) {
            addCriterion("drug_specifications <=", value, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsLike(String value) {
            addCriterion("drug_specifications like", value, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsNotLike(String value) {
            addCriterion("drug_specifications not like", value, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsIn(List<String> values) {
            addCriterion("drug_specifications in", values, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsNotIn(List<String> values) {
            addCriterion("drug_specifications not in", values, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsBetween(String value1, String value2) {
            addCriterion("drug_specifications between", value1, value2, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andDrugSpecificationsNotBetween(String value1, String value2) {
            addCriterion("drug_specifications not between", value1, value2, "drugSpecifications");
            return (Criteria) this;
        }

        public Criteria andIsantibioticIsNull() {
            addCriterion("isAntibiotic is null");
            return (Criteria) this;
        }

        public Criteria andIsantibioticIsNotNull() {
            addCriterion("isAntibiotic is not null");
            return (Criteria) this;
        }

        public Criteria andIsantibioticEqualTo(Short value) {
            addCriterion("isAntibiotic =", value, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andIsantibioticNotEqualTo(Short value) {
            addCriterion("isAntibiotic <>", value, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andIsantibioticGreaterThan(Short value) {
            addCriterion("isAntibiotic >", value, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andIsantibioticGreaterThanOrEqualTo(Short value) {
            addCriterion("isAntibiotic >=", value, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andIsantibioticLessThan(Short value) {
            addCriterion("isAntibiotic <", value, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andIsantibioticLessThanOrEqualTo(Short value) {
            addCriterion("isAntibiotic <=", value, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andIsantibioticIn(List<Short> values) {
            addCriterion("isAntibiotic in", values, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andIsantibioticNotIn(List<Short> values) {
            addCriterion("isAntibiotic not in", values, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andIsantibioticBetween(Short value1, Short value2) {
            addCriterion("isAntibiotic between", value1, value2, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andIsantibioticNotBetween(Short value1, Short value2) {
            addCriterion("isAntibiotic not between", value1, value2, "isantibiotic");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeIsNull() {
            addCriterion("hospital_code is null");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeIsNotNull() {
            addCriterion("hospital_code is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeEqualTo(String value) {
            addCriterion("hospital_code =", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeNotEqualTo(String value) {
            addCriterion("hospital_code <>", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeGreaterThan(String value) {
            addCriterion("hospital_code >", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_code >=", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeLessThan(String value) {
            addCriterion("hospital_code <", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeLessThanOrEqualTo(String value) {
            addCriterion("hospital_code <=", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeLike(String value) {
            addCriterion("hospital_code like", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeNotLike(String value) {
            addCriterion("hospital_code not like", value, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeIn(List<String> values) {
            addCriterion("hospital_code in", values, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeNotIn(List<String> values) {
            addCriterion("hospital_code not in", values, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeBetween(String value1, String value2) {
            addCriterion("hospital_code between", value1, value2, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andHospitalCodeNotBetween(String value1, String value2) {
            addCriterion("hospital_code not between", value1, value2, "hospitalCode");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNull() {
            addCriterion("record_status is null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNotNull() {
            addCriterion("record_status is not null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusEqualTo(Integer value) {
            addCriterion("record_status =", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotEqualTo(Integer value) {
            addCriterion("record_status <>", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThan(Integer value) {
            addCriterion("record_status >", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_status >=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThan(Integer value) {
            addCriterion("record_status <", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThanOrEqualTo(Integer value) {
            addCriterion("record_status <=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIn(List<Integer> values) {
            addCriterion("record_status in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotIn(List<Integer> values) {
            addCriterion("record_status not in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusBetween(Integer value1, Integer value2) {
            addCriterion("record_status between", value1, value2, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("record_status not between", value1, value2, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andExtractTimeIsNull() {
            addCriterion("extract_time is null");
            return (Criteria) this;
        }

        public Criteria andExtractTimeIsNotNull() {
            addCriterion("extract_time is not null");
            return (Criteria) this;
        }

        public Criteria andExtractTimeEqualTo(Date value) {
            addCriterion("extract_time =", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeNotEqualTo(Date value) {
            addCriterion("extract_time <>", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeGreaterThan(Date value) {
            addCriterion("extract_time >", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("extract_time >=", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeLessThan(Date value) {
            addCriterion("extract_time <", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeLessThanOrEqualTo(Date value) {
            addCriterion("extract_time <=", value, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeIn(List<Date> values) {
            addCriterion("extract_time in", values, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeNotIn(List<Date> values) {
            addCriterion("extract_time not in", values, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeBetween(Date value1, Date value2) {
            addCriterion("extract_time between", value1, value2, "extractTime");
            return (Criteria) this;
        }

        public Criteria andExtractTimeNotBetween(Date value1, Date value2) {
            addCriterion("extract_time not between", value1, value2, "extractTime");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNull() {
            addCriterion("attribute1 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNotNull() {
            addCriterion("attribute1 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute1EqualTo(String value) {
            addCriterion("attribute1 =", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotEqualTo(String value) {
            addCriterion("attribute1 <>", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThan(String value) {
            addCriterion("attribute1 >", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThanOrEqualTo(String value) {
            addCriterion("attribute1 >=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThan(String value) {
            addCriterion("attribute1 <", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThanOrEqualTo(String value) {
            addCriterion("attribute1 <=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Like(String value) {
            addCriterion("attribute1 like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotLike(String value) {
            addCriterion("attribute1 not like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1In(List<String> values) {
            addCriterion("attribute1 in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotIn(List<String> values) {
            addCriterion("attribute1 not in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Between(String value1, String value2) {
            addCriterion("attribute1 between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotBetween(String value1, String value2) {
            addCriterion("attribute1 not between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNull() {
            addCriterion("attribute2 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNotNull() {
            addCriterion("attribute2 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute2EqualTo(String value) {
            addCriterion("attribute2 =", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotEqualTo(String value) {
            addCriterion("attribute2 <>", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThan(String value) {
            addCriterion("attribute2 >", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThanOrEqualTo(String value) {
            addCriterion("attribute2 >=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThan(String value) {
            addCriterion("attribute2 <", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThanOrEqualTo(String value) {
            addCriterion("attribute2 <=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Like(String value) {
            addCriterion("attribute2 like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotLike(String value) {
            addCriterion("attribute2 not like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2In(List<String> values) {
            addCriterion("attribute2 in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotIn(List<String> values) {
            addCriterion("attribute2 not in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Between(String value1, String value2) {
            addCriterion("attribute2 between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotBetween(String value1, String value2) {
            addCriterion("attribute2 not between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNull() {
            addCriterion("attribute3 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNotNull() {
            addCriterion("attribute3 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute3EqualTo(String value) {
            addCriterion("attribute3 =", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotEqualTo(String value) {
            addCriterion("attribute3 <>", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThan(String value) {
            addCriterion("attribute3 >", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThanOrEqualTo(String value) {
            addCriterion("attribute3 >=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThan(String value) {
            addCriterion("attribute3 <", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThanOrEqualTo(String value) {
            addCriterion("attribute3 <=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Like(String value) {
            addCriterion("attribute3 like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotLike(String value) {
            addCriterion("attribute3 not like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3In(List<String> values) {
            addCriterion("attribute3 in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotIn(List<String> values) {
            addCriterion("attribute3 not in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Between(String value1, String value2) {
            addCriterion("attribute3 between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotBetween(String value1, String value2) {
            addCriterion("attribute3 not between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute4IsNull() {
            addCriterion("attribute4 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute4IsNotNull() {
            addCriterion("attribute4 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute4EqualTo(String value) {
            addCriterion("attribute4 =", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotEqualTo(String value) {
            addCriterion("attribute4 <>", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4GreaterThan(String value) {
            addCriterion("attribute4 >", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4GreaterThanOrEqualTo(String value) {
            addCriterion("attribute4 >=", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4LessThan(String value) {
            addCriterion("attribute4 <", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4LessThanOrEqualTo(String value) {
            addCriterion("attribute4 <=", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4Like(String value) {
            addCriterion("attribute4 like", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotLike(String value) {
            addCriterion("attribute4 not like", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4In(List<String> values) {
            addCriterion("attribute4 in", values, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotIn(List<String> values) {
            addCriterion("attribute4 not in", values, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4Between(String value1, String value2) {
            addCriterion("attribute4 between", value1, value2, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotBetween(String value1, String value2) {
            addCriterion("attribute4 not between", value1, value2, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute5IsNull() {
            addCriterion("attribute5 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute5IsNotNull() {
            addCriterion("attribute5 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute5EqualTo(String value) {
            addCriterion("attribute5 =", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotEqualTo(String value) {
            addCriterion("attribute5 <>", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5GreaterThan(String value) {
            addCriterion("attribute5 >", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5GreaterThanOrEqualTo(String value) {
            addCriterion("attribute5 >=", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5LessThan(String value) {
            addCriterion("attribute5 <", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5LessThanOrEqualTo(String value) {
            addCriterion("attribute5 <=", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5Like(String value) {
            addCriterion("attribute5 like", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotLike(String value) {
            addCriterion("attribute5 not like", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5In(List<String> values) {
            addCriterion("attribute5 in", values, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotIn(List<String> values) {
            addCriterion("attribute5 not in", values, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5Between(String value1, String value2) {
            addCriterion("attribute5 between", value1, value2, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotBetween(String value1, String value2) {
            addCriterion("attribute5 not between", value1, value2, "attribute5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}